version: 2
jobs:
  build:
    working-directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
deployment:
  staging:
    branch: master
    owner: rainede
    heroku:
      appname: ci-demo-app
